#! usr/bin/env python3

# Advent of Code Day 4-B

import sys

# Functions

def read_camp_cleanup():
    overlap = 0
    
    for line in sys.stdin:
        first_range, second_range = line.rstrip().split(',')
        first_start, first_end = first_range.split('-')
        second_start, second_end = second_range.split('-')
        first_set = set(i for i in range(int(first_start), int(first_end)+1))

        for i in range(int(second_start), int(second_end)+1):
            if i in first_set:
                overlap += 1
                break

    return overlap

# Main Execution

def main():
    overlap = read_camp_cleanup()
    print(f'Day 4-B: {overlap}')

if __name__ == '__main__':
    main()
