#! bin/usr/env python3

# Advent of Code Day 2-A

import sys

# Functions

def read_rps():
    score = 0
    check_score = {1: {1: 4, 2: 8, 3: 3},
                   2: {1: 1, 2: 5, 3: 9},
                   3: {1: 7, 2: 2, 3: 6}}

    for line in sys.stdin:
        opponent, response = ord(line.split()[0])-64, ord(line.split()[1])-87
        score += check_score[opponent][response]
    
    return score

# Main Execution

def main():
    score = read_rps()
    print(f'Day 2-A: {score}')
    
if __name__ == '__main__':
    main()
